version: "3.8"

services:
  db:
    image: postgres:alpine
    ports:
      - "1414:1414"
    command: [ "postgres", "-p", "1414" ]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: wrm1
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: