spring:
  datasource:
    url: jdbc:postgresql://localhost:1414/wrm1
    username: postgres
    password: 123

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

waiting-room:
  default-algorithm-type: FIFO
  default-work-mode: MORNING
  default-capacity: 15

visit:
  default-visitor-status: WAITING